@version: current

options {
    time-reap(30);
    mark-freq(10);
    keep-hostname(yes);
};

source s_net {
    udp(port(514));
    tcp(port(514));
};

destination d_mysql {
    sql(
        type(mysql)
        host("db")
        username("rsyslog")
        password("rsyslog_password")
        database("rsyslog")
        table("SystemEvents")
        columns("ReceivedAt", "DeviceReportedTime", "Facility", "Priority", "FromHost", "Message", "SysLogTag")
        values("${R_DATE}", "${ISODATE}", "${FACILITY_NUM}", "${PRIORITY}", "${HOST}", "${MSG}", "${PROGRAM}")
        indexes("ReceivedAt", "DeviceReportedTime", "Facility", "Priority", "FromHost")
    );
};

log {
    source(s_net);
    destination(d_mysql);
}; 