# Load modules
module(load="imudp")
module(load="imtcp")
module(load="ommysql")

# UDP input
input(type="imudp" port="514")

# TCP input
input(type="imtcp" port="514")

# MySQL output
template(name="sql-syslog" type="string" string="INSERT INTO SystemEvents (ReceivedAt, DeviceReportedTime, Facility, Priority, FromHost, Message, SysLogTag) VALUES ('%$NOW%', '%$TIMESTAMP:::date-mysql%', %syslogfacility%, %syslogpriority%, '%HOSTNAME%', '%msg:::sql%', '%syslogtag:::sql%')")

# Write to MySQL
action(type="ommysql" 
    server=`echo $MYSQL_HOST`
    db=`echo $MYSQL_DATABASE`
    uid=`echo $MYSQL_USER`
    pwd=`echo $MYSQL_PASSWORD`
    template="sql-syslog"
) 